"""baseline: full current schema (16 tables).

Autogenerated from BaseDatastore.Base.metadata (importing jubu_datastore
registers every model) and hand-reviewed. Matches the ORM models exactly —
scripts/verify_migrations.py asserts zero autogenerate drift after upgrade.

Fresh databases: `alembic upgrade head` from empty creates everything.
Pre-Alembic databases (schema built by create_all + the manual scripts in
migrations/): run `alembic stamp 0001`, then `alembic upgrade head` — revision
0002 conditionally aligns any legacy leftovers.

This baseline absorbs, for fresh installs, the intent of every manual script
in migrations/ (capability_001, conversation_002/003, parent_chat_001,
consent_001, topics_001, observed_interests_001/002, profile_001, user_001,
interaction_contexts_001); each is marked SUPERSEDED in place and kept until
the Alembic history is verified against production.

Revision ID: 0001
Revises:
Create Date: 2026-07-03

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "child_capability_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=False),
        sa.Column("item_id", sa.String(length=255), nullable=False),
        sa.Column("item_version", sa.Integer(), nullable=False),
        sa.Column("framework", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=64), nullable=False),
        sa.Column("subdomain", sa.String(length=64), nullable=False),
        sa.Column("observation_status", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("evidence_text", sa.Text(), nullable=True),
        sa.Column("evaluator_type", sa.String(length=64), nullable=False),
        sa.Column("evaluator_version", sa.String(length=64), nullable=True),
        sa.Column("raw_score_json", sa.JSON(), nullable=True),
        sa.Column("observed_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("child_capability_observations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_obs_child_framework", ["child_id", "framework"], unique=False
        )
        batch_op.create_index(
            "idx_obs_child_item", ["child_id", "item_id"], unique=False
        )
        batch_op.create_index("idx_obs_item_id", ["item_id"], unique=False)
        batch_op.create_index("idx_obs_session", ["session_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_child_capability_observations_child_id"),
            ["child_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_child_capability_observations_framework"),
            ["framework"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_child_capability_observations_observed_at"),
            ["observed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_child_capability_observations_session_id"),
            ["session_id"],
            unique=False,
        )

    op.create_table(
        "child_capability_state",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("item_id", sa.String(length=255), nullable=False),
        sa.Column("item_version", sa.Integer(), nullable=False),
        sa.Column("framework", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=64), nullable=False),
        sa.Column("subdomain", sa.String(length=64), nullable=False),
        sa.Column("current_status", sa.String(length=64), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("mastery_score", sa.Float(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("first_observed_at", sa.DateTime(), nullable=True),
        sa.Column("last_observed_at", sa.DateTime(), nullable=True),
        sa.Column("last_session_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "mastery_score >= 0 AND mastery_score <= 1", name="chk_mastery_score_range"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "child_id", "item_id", name="uq_child_capability_state_child_item"
        ),
    )
    with op.batch_alter_table("child_capability_state", schema=None) as batch_op:
        batch_op.create_index(
            "idx_state_child_framework", ["child_id", "framework"], unique=False
        )
        batch_op.create_index(
            "idx_state_child_item", ["child_id", "item_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_child_capability_state_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_child_capability_state_framework"),
            ["framework"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_child_capability_state_item_id"), ["item_id"], unique=False
        )

    op.create_table(
        "child_facts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("source_turn_id", sa.String(length=36), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("expiration", sa.DateTime(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("child_facts", schema=None) as batch_op:
        batch_op.create_index(
            "idx_child_active_expiration",
            ["child_id", "active", "expiration"],
            unique=False,
        )
        batch_op.create_index("idx_expiration", ["expiration"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_child_facts_active"), ["active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_child_facts_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_child_facts_expiration"), ["expiration"], unique=False
        )

    op.create_table(
        "consent_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("direct_notice_version", sa.String(length=64), nullable=True),
        sa.Column("privacy_policy_version", sa.String(length=32), nullable=True),
        sa.Column("vpc_method", sa.String(length=32), nullable=True),
        sa.Column("apple_transaction_id", sa.String(length=255), nullable=True),
        sa.Column("child_id", sa.String(length=36), nullable=True),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    with op.batch_alter_table("consent_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_consent_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_consent_events_parent_id"), ["parent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_consent_events_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "conversations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("last_interaction_time", sa.DateTime(), nullable=False),
        sa.Column("conv_metadata", sa.JSON(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("parent_summary", sa.Text(), nullable=True),
        sa.Column("parent_highlights", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_archived_time", ["is_archived", "start_time"], unique=False
        )
        batch_op.create_index(
            "idx_child_state_time", ["child_id", "state", "start_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_is_archived"), ["is_archived"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_start_time"), ["start_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_state"), ["state"], unique=False
        )

    op.create_table(
        "inferred_traits",
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("curiosity_mode_by_kind", sa.JSON(), nullable=False),
        sa.Column("preferred_style", sa.String(length=64), nullable=True),
        sa.Column("preferred_style_confidence", sa.Float(), nullable=True),
        sa.Column("voice_style_scores", sa.JSON(), nullable=False),
        sa.Column("evidence_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("child_id"),
    )
    op.create_table(
        "observed_interests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("canonical_key", sa.String(length=120), nullable=False),
        sa.Column("interest_label", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("framework_link", sa.String(length=255), nullable=True),
        sa.Column("times_visited", sa.Integer(), nullable=False),
        sa.Column("total_mentions", sa.Integer(), nullable=False),
        sa.Column("origin", sa.String(length=8), nullable=False),
        sa.Column("first_session_id", sa.String(length=36), nullable=True),
        sa.Column("last_session_id", sa.String(length=36), nullable=True),
        sa.Column("first_observed_at", sa.DateTime(), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(), nullable=False),
        sa.Column("last_depth", sa.Integer(), nullable=False),
        sa.Column("breadth_count", sa.Integer(), nullable=False),
        sa.Column("curiosity_signal", sa.Float(), nullable=True),
        sa.Column("sentiment", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "child_id", "canonical_key", name="uq_child_observed_interest"
        ),
    )
    with op.batch_alter_table("observed_interests", schema=None) as batch_op:
        batch_op.create_index("idx_observed_interest_child", ["child_id"], unique=False)
        batch_op.create_index(
            "idx_observed_interest_child_recent",
            ["child_id", "last_observed_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_observed_interests_child_id"), ["child_id"], unique=False
        )

    op.create_table(
        "parent_chat_rolling_summary",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("session_count", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "parent_id", "child_id", name="uq_rolling_summary_parent_child"
        ),
    )
    op.create_table(
        "parent_chat_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("scenario_key", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_message_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("summary_generated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("parent_chat_sessions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_pcs_parent_active", ["parent_id", "is_active"], unique=False
        )
        batch_op.create_index(
            "idx_pcs_parent_created", ["parent_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_parent_chat_sessions_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_parent_chat_sessions_parent_id"), ["parent_id"], unique=False
        )

    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=False),
        sa.Column("apple_transaction_id", sa.String(length=255), nullable=False),
        sa.Column(
            "apple_original_transaction_id", sa.String(length=255), nullable=False
        ),
        sa.Column("product_id", sa.String(length=128), nullable=False),
        sa.Column("purchase_date", sa.DateTime(), nullable=False),
        sa.Column("expires_date", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("receipt_data", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("subscription_id"),
        sa.UniqueConstraint("apple_transaction_id"),
    )
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subscriptions_parent_id"), ["parent_id"], unique=False
        )

    op.create_table(
        "telemetry_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column("child_id", sa.String(length=36), nullable=True),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("telemetry_events", schema=None) as batch_op:
        batch_op.create_index("idx_events_event_ts", ["event", "ts"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_telemetry_events_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_telemetry_events_conversation_id"),
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_telemetry_events_event"), ["event"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_telemetry_events_ts"), ["ts"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=True),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index("idx_email_active", ["email", "is_active"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "child_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("parent_declared_interests", sa.JSON(), nullable=False),
        sa.Column("preferences", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_interaction", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("child_profiles", schema=None) as batch_op:
        batch_op.create_index(
            "idx_active_parent", ["is_active", "parent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_child_profiles_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_child_profiles_parent_id"), ["parent_id"], unique=False
        )

    op.create_table(
        "conversation_turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("child_message", sa.Text(), nullable=False),
        sa.Column("system_message", sa.Text(), nullable=True),
        sa.Column("interaction_type", sa.String(length=50), nullable=False),
        sa.Column("safety_evaluation", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("conversation_turns", schema=None) as batch_op:
        batch_op.create_index(
            "idx_conversation_time", ["conversation_id", "timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_turns_conversation_id"),
            ["conversation_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_conversation_turns_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "parent_chat_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["parent_chat_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("parent_chat_messages", schema=None) as batch_op:
        batch_op.create_index(
            "idx_pcm_session_time", ["session_id", "timestamp"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_parent_chat_messages_session_id"),
            ["session_id"],
            unique=False,
        )

    op.create_table(
        "stories",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("child_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("last_viewed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stories", schema=None) as batch_op:
        batch_op.create_index(
            "idx_child_favorite", ["child_id", "is_favorite"], unique=False
        )
        batch_op.create_index("idx_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_stories_child_id"), ["child_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stories_conversation_id"), ["conversation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stories_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_stories_child_id"))
        batch_op.drop_index("idx_created_at")
        batch_op.drop_index("idx_child_favorite")

    op.drop_table("stories")
    with op.batch_alter_table("parent_chat_messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parent_chat_messages_session_id"))
        batch_op.drop_index("idx_pcm_session_time")

    op.drop_table("parent_chat_messages")
    with op.batch_alter_table("conversation_turns", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversation_turns_timestamp"))
        batch_op.drop_index(batch_op.f("ix_conversation_turns_conversation_id"))
        batch_op.drop_index("idx_conversation_time")

    op.drop_table("conversation_turns")
    with op.batch_alter_table("child_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_child_profiles_parent_id"))
        batch_op.drop_index(batch_op.f("ix_child_profiles_is_active"))
        batch_op.drop_index("idx_active_parent")

    op.drop_table("child_profiles")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))
        batch_op.drop_index("idx_email_active")

    op.drop_table("users")
    with op.batch_alter_table("telemetry_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_telemetry_events_ts"))
        batch_op.drop_index(batch_op.f("ix_telemetry_events_event"))
        batch_op.drop_index(batch_op.f("ix_telemetry_events_conversation_id"))
        batch_op.drop_index(batch_op.f("ix_telemetry_events_child_id"))
        batch_op.drop_index("idx_events_event_ts")

    op.drop_table("telemetry_events")
    with op.batch_alter_table("subscriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subscriptions_parent_id"))

    op.drop_table("subscriptions")
    with op.batch_alter_table("parent_chat_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_parent_chat_sessions_parent_id"))
        batch_op.drop_index(batch_op.f("ix_parent_chat_sessions_child_id"))
        batch_op.drop_index("idx_pcs_parent_created")
        batch_op.drop_index("idx_pcs_parent_active")

    op.drop_table("parent_chat_sessions")
    op.drop_table("parent_chat_rolling_summary")
    with op.batch_alter_table("observed_interests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_observed_interests_child_id"))
        batch_op.drop_index("idx_observed_interest_child_recent")
        batch_op.drop_index("idx_observed_interest_child")

    op.drop_table("observed_interests")
    op.drop_table("inferred_traits")
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_state"))
        batch_op.drop_index(batch_op.f("ix_conversations_start_time"))
        batch_op.drop_index(batch_op.f("ix_conversations_is_archived"))
        batch_op.drop_index(batch_op.f("ix_conversations_child_id"))
        batch_op.drop_index("idx_child_state_time")
        batch_op.drop_index("idx_archived_time")

    op.drop_table("conversations")
    with op.batch_alter_table("consent_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_consent_events_timestamp"))
        batch_op.drop_index(batch_op.f("ix_consent_events_parent_id"))
        batch_op.drop_index(batch_op.f("ix_consent_events_event_type"))

    op.drop_table("consent_events")
    with op.batch_alter_table("child_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_child_facts_expiration"))
        batch_op.drop_index(batch_op.f("ix_child_facts_child_id"))
        batch_op.drop_index(batch_op.f("ix_child_facts_active"))
        batch_op.drop_index("idx_expiration")
        batch_op.drop_index("idx_child_active_expiration")

    op.drop_table("child_facts")
    with op.batch_alter_table("child_capability_state", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_child_capability_state_item_id"))
        batch_op.drop_index(batch_op.f("ix_child_capability_state_framework"))
        batch_op.drop_index(batch_op.f("ix_child_capability_state_child_id"))
        batch_op.drop_index("idx_state_child_item")
        batch_op.drop_index("idx_state_child_framework")

    op.drop_table("child_capability_state")
    with op.batch_alter_table("child_capability_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_child_capability_observations_session_id"))
        batch_op.drop_index(batch_op.f("ix_child_capability_observations_observed_at"))
        batch_op.drop_index(batch_op.f("ix_child_capability_observations_framework"))
        batch_op.drop_index(batch_op.f("ix_child_capability_observations_child_id"))
        batch_op.drop_index("idx_obs_session")
        batch_op.drop_index("idx_obs_item_id")
        batch_op.drop_index("idx_obs_child_item")
        batch_op.drop_index("idx_obs_child_framework")

    op.drop_table("child_capability_observations")
    # ### end Alembic commands ###
