"""Build the deployable buju.ai/pilot assets from the pilot story library.

Outputs (under story_definitions/preview/pilot_site/):

  data/stories.json      parent-facing story data: full prose + choices + slots,
                         but NO build_record / gate findings / R&D internals.
  explorer/index.html    the admin story explorer, with its script split out to
  explorer/explorer.js   an external file so it can ship under the website's
                         CSP (script-src 'self' forbids inline scripts).

Run from the repo root as:  python scripts/build_pilot_site.py
(never `python -m`, never with PYTHONPATH=. — the repo's logging/ package
shadows stdlib logging when the root is sys.path[0]).

The parent page itself (HTML/CSS/JS) is hand-authored in the buju_website
repo under pilot/ — this script only produces the data + explorer artifacts
that get copied there.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path
from typing import Any

import build_story_explorer as bse  # same directory; reuse loader + validator
import story_audio_chunks

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "story_definitions" / "preview" / "pilot_site"
EXPLORER_HTML = REPO_ROOT / "story_definitions" / "preview" / "story_explorer.html"
AUDIO_MANIFEST = REPO_ROOT / "story_definitions" / "audio_manifest.json"

# Split markers for the single inline <script> in the built explorer.
# split/join only — no regex, no .replace() (see STORY_EXPLORER_SPEC.md).
SCRIPT_OPEN = "<script>"
SCRIPT_CLOSE = "</script>"


def _reading_minutes(story: dict[str, Any]) -> int:
    """Rough read-aloud minutes for the longest path (~140 wpm aloud)."""
    segments = {seg["id"]: seg for seg in story["segments"]}
    words_a = 0
    words_b = 0
    for seg_id, seg in segments.items():
        n = len(seg["text"].split())
        if seg_id.endswith("a"):
            words_a += n
        elif seg_id.endswith("b"):
            words_b += n
        else:
            words_a += n
            words_b += n
    minutes = max(words_a, words_b) / 140.0
    return max(2, round(minutes))


def load_audio_manifest() -> dict[str, Any]:
    """Narration clips generated by generate_story_audio.py, or {} when no
    story has been voiced yet."""
    if not AUDIO_MANIFEST.is_file():
        return {}
    with open(AUDIO_MANIFEST, encoding="utf-8") as f:
        return json.load(f)


def story_audio_field(
    story: dict[str, Any], manifest_entry: dict[str, Any]
) -> dict[str, Any] | None:
    """The parent-facing `audio` field for one voiced story, or None when the
    manifest is stale (story prose changed since generation — regenerate).

    Per unit (segment or choice question), a list over paragraph chunks:
    {"i": chunk index, "file": mp3 under /pilot/audio/<story_id>/,
     "has_slot": chunk contains a {slot} so the player re-voices it live
     with the chosen name (this mp3 is the default-name fallback)}.
    """
    slots = story.get("slots") or {}
    unit_prose = {segment["id"]: segment["text"] for segment in story["segments"]}
    unit_prose.update(
        (choice_point["id"], choice_point["question"])
        for choice_point in story["choice_points"]
    )
    manifest_segments = manifest_entry.get("segments", {})
    stamped_segments: dict[str, list[dict[str, Any]]] = {}
    for unit_id, prose in unit_prose.items():
        chunks = story_audio_chunks.paragraph_chunks(prose)
        manifest_chunks = manifest_segments.get(unit_id)
        if manifest_chunks is None or len(manifest_chunks) != len(chunks):
            print(
                f"WARNING: audio manifest is stale for {story['id']} "
                f"(unit {unit_id}) — skipping its audio; re-run "
                f"generate_story_audio.py for this story"
            )
            return None
        stamped_segments[unit_id] = [
            {
                "i": chunk_entry["i"],
                "file": chunk_entry["file"],
                "has_slot": bool(
                    story_audio_chunks.declared_slot_tokens(chunks[chunk_entry["i"]], slots)
                ),
            }
            for chunk_entry in manifest_chunks
        ]
    audio_field = {
        # Delivery settings ride along so the read-time name-narration
        # endpoint re-voices chunks to match the pre-generated clips
        # exactly — same voice, pace, emotion and sentence pauses.
        "voice_id": manifest_entry["voice_id"],
        "model_id": manifest_entry["model_id"],
        "speed": manifest_entry.get("speed", 1.0),
        "sentence_pause_ms": manifest_entry.get("sentence_pause_ms", 0),
        "segments": stamped_segments,
    }
    if manifest_entry.get("emotion"):
        audio_field["emotion"] = manifest_entry["emotion"]
    return audio_field


def build_parent_data(stories: list[dict[str, Any]]) -> dict[str, Any]:
    registry = bse.load_default_registry()
    audio_manifest = load_audio_manifest()
    topics: dict[str, str] = {}
    out_stories: list[dict[str, Any]] = []
    for story in sorted(stories, key=lambda s: (s["title"])):
        topic_id = story["topics"]["knowledge_domain"]
        if topic_id not in topics:
            node = registry.get_node(topic_id)
            topics[topic_id] = node.display_name if node else topic_id.split(".")[-1]
        segments = {
            seg["id"]: {"text": seg["text"], "next": seg["next"]}
            for seg in story["segments"]
        }
        choices = {
            cp["id"]: {
                "question": cp["question"],
                "rejoins": cp["rejoins"],
                "options": [
                    {
                        "say_word": opt["say_word"],
                        "label": opt["label"],
                        "next_segment": opt["next_segment"],
                        "sets_slots": opt.get("sets_slots", {}),
                    }
                    for opt in cp["options"]
                ],
            }
            for cp in story["choice_points"]
        }
        slots = {
            name: {
                "role": slot["role"],
                "kind": slot["kind"],
                "ask_child": slot["ask_child"],
                "default": slot["default"],
            }
            for name, slot in story["slots"].items()
        }
        parent_story = {
            "id": story["id"],
            "title": story["title"],
            "age_band": story["age_band"],
            "topic": topic_id,
            "depth": story["depth"],
            "minutes": _reading_minutes(story),
            "start": story["start_segment"],
            "segments": segments,
            "choices": choices,
            "slots": slots,
        }
        if story["id"] in audio_manifest:
            audio_field = story_audio_field(story, audio_manifest[story["id"]])
            if audio_field is not None:
                parent_story["audio"] = audio_field
        out_stories.append(parent_story)
    return {
        "topics": topics,
        "stories": out_stories,
        "graph": build_parent_graph(stories),
    }


# Similarity super-groups for the parent map: wedges laid out in this order
# around the disc, so neighbouring wedges hold related themes (space→earth→
# water→life→food→mind→arts→machines→space). Categories inside a group
# cluster tightly; their deep dives ring each category. Every category in
# build_story_explorer.PILOT_CATEGORIES must appear exactly once here —
# the build fails loudly if the two lists drift apart.
_KD = "knowledge_domain."
PARENT_MAP_GROUPS: list[tuple[str, list[str]]] = [
    ("space", ["planets", "the_solar_system", "the_moon", "the_sun",
               "stars_and_constellations", "black_holes", "comets_and_meteors",
               "gravity", "astronauts_and_space_travel", "day_and_night"]),
    ("earth", ["volcanoes", "earthquakes", "plate_tectonics",
               "rocks_and_minerals", "islands", "weather", "maps_and_globes"]),
    ("water", ["oceans_and_tides", "ocean_animals", "whales_and_dolphins",
               "frogs_and_amphibians"]),
    ("life", ["insects", "birds", "rainforests", "dinosaurs",
              "ecosystems", "endangered_animals"]),
    ("food", ["farms_and_food"]),
    ("mind", ["the_brain", "sleep_and_dreams", "genes_and_heredity"]),
    ("arts", ["musical_instruments", "sound_and_echoes", "drawing_and_animation",
              "theater_and_pretending", "shapes_and_symmetry"]),
    ("machines", ["computers_and_code", "robots", "engines_and_vehicles",
                  "magnets", "inventions"]),
]

# Front-hemisphere disc layout: flat enough that nothing hides behind
# anything under the map's clamped "fake" rotation, with a gentle z bulge
# for parallax. y is compressed to suit the wide viewBox.
# Each similarity group owns a pie wedge (angle proportional to how many
# nodes it holds). Inside its wedge a group's categories are spread from
# near the centre out to the rim — so the disc is filled edge to edge with
# no hollow middle, while every group still reads as one contiguous slice.
R_MIN = 46.0
R_MAX = 268.0
Y_SQUASH = 0.74
BULGE_RADIUS = 390.0
GOLDEN = 0.6180339887498949


def _child_ring(count: int) -> float:
    """Deep-dive ring radius, scaled so siblings keep ~30px spacing."""
    return min(62.0, max(38.0, 4.8 * count))


def _disc_positions(child_counts: dict[str, int]) -> dict[str, tuple[float, float, float]]:
    grouped = [(g, cats) for g, cats in PARENT_MAP_GROUPS]
    listed = [c for _, cats in grouped for c in cats]
    expected = sorted(bse.PILOT_CATEGORIES)
    if sorted(_KD + c for c in listed) != expected:
        missing = set(expected) - {_KD + c for c in listed}
        extra = {_KD + c for c in listed} - set(expected)
        raise SystemExit(
            f"PARENT_MAP_GROUPS out of sync with PILOT_CATEGORIES: "
            f"missing={sorted(missing)} extra={sorted(extra)}"
        )
    # Wedge angle follows how much stuff a group actually holds (its
    # categories plus their deep dives), so dense groups get room and
    # sparse ones don't leave a gap.
    weights = [
        sum(1 + child_counts.get(_KD + c, 0) for c in cats) for _, cats in grouped
    ]
    total_w = float(sum(weights))
    pos: dict[str, tuple[float, float, float]] = {}
    theta = 0.0
    for (_, cats), w in zip(grouped, weights):
        wedge = 2.0 * math.pi * (w / total_w)
        k = len(cats)
        for i, cat in enumerate(cats):
            frac = (i + 0.5) / k
            # radius walks centre -> rim across the group's categories, so
            # every wedge covers the whole radius and the middle stays full
            r = R_MIN + (R_MAX - R_MIN) * (frac ** 0.78)
            if k == 1:
                a = theta + wedge * 0.5
            else:
                # golden-ratio stagger inside the wedge: even angular fill
                # without categories lining up on one spoke
                a = theta + wedge * (0.12 + 0.76 * ((i * GOLDEN) % 1.0))
            x = r * math.cos(a)
            y = r * math.sin(a) * Y_SQUASH
            pos[_KD + cat] = (round(x, 2), round(y, 2), a)
        theta += wedge
    return pos


def _bulge(x: float, y: float) -> float:
    d2 = x * x + (y / Y_SQUASH) ** 2
    return round(0.5 * math.sqrt(max(0.0, BULGE_RADIUS ** 2 - d2)) - 60.0, 2)


def build_parent_graph(stories: list[dict[str, Any]]) -> dict[str, Any]:
    """The topic map for the parent page: positions + edges + story counts.

    Unlike the admin explorer's full sphere, the parent map is a clustered
    front-facing disc: similarity super-groups sit in adjacent wedges,
    categories cluster inside their wedge, deep dives ring their category,
    and a mild z bulge gives parallax under the page's clamped rotation.
    Ships ONLY parent-safe fields — no framing / vocabulary / avoid lists.
    """
    expl = bse.build_explorer_data(stories)  # reuse counts, names, edges
    child_counts: dict[str, int] = {}
    for t in expl["topics"]:
        if t["parent"]:
            child_counts[t["parent"]] = child_counts.get(t["parent"], 0) + 1
    cat_pos = _disc_positions(child_counts)

    nodes: list[dict[str, Any]] = []
    for t in expl["topics"]:
        if t["parent"] is None:
            if t["id"] not in cat_pos:
                continue
            x, y, _a = cat_pos[t["id"]]
        else:
            px, py, pa = cat_pos[t["parent"]]
            siblings = sorted(
                s["id"] for s in expl["topics"] if s["parent"] == t["parent"]
            )
            idx = siblings.index(t["id"])
            count = len(siblings)
            # full ring around the category, rotated to face outward first
            rc = _child_ring(count)
            a = pa + idx * (2.0 * math.pi / count)
            x = round(px + rc * math.cos(a), 2)
            y = round(py + rc * math.sin(a) * Y_SQUASH, 2)
        nodes.append(
            {
                "id": t["id"],
                "name": t["display_name"],
                "x": x,
                "y": y,
                "z": _bulge(x, y),
                "cluster": t["cluster"],
                "parent": t["parent"],
                "stories": t["stories"],
            }
        )

    _relax(nodes, {cid: (p[0], p[1]) for cid, p in cat_pos.items()})

    kept = {n["id"] for n in nodes}
    edges = [
        {"source": e["source"], "target": e["target"]}
        for e in expl["edges"]
        if e["source"] in kept and e["target"] in kept
    ]
    return {"nodes": nodes, "edges": edges}


MIN_NODE_SPACING = 34.0
CATEGORY_DRIFT = 0.35   # how freely a category may shift while packing
ANCHOR_SPRING = 0.22    # ...and how hard it is pulled back to its wedge slot


def _relax(
    nodes: list[dict[str, Any]],
    anchors: dict[str, tuple[float, float]],
    rounds: int = 90,
) -> None:
    """Push overlapping nodes apart, then spring categories back toward the
    wedge slot they were assigned. Deep dives move freely; categories only
    drift a little, so groups stay contiguous while the disc packs evenly.
    Fully deterministic — no randomness (positions must be stable builds)."""
    for step in range(rounds):
        # anneal the spring to zero so the last rounds are pure separation —
        # groups are already settled by then, and spacing wins at the end
        spring = ANCHOR_SPRING * max(0.0, 1.0 - step / (rounds * 0.6))
        moved = False
        for i in range(len(nodes)):
            for j in range(i + 1, len(nodes)):
                a, b = nodes[i], nodes[j]
                dx = b["x"] - a["x"]
                dy = b["y"] - a["y"]
                d = math.sqrt(dx * dx + dy * dy)
                if d >= MIN_NODE_SPACING:
                    continue
                if d < 1e-6:
                    dx, dy, d = 1.0, 0.5, 1.118
                push = (MIN_NODE_SPACING - d) / 2.0
                ux, uy = dx / d, dy / d
                wa = CATEGORY_DRIFT if a["parent"] is None else 1.0
                wb = CATEGORY_DRIFT if b["parent"] is None else 1.0
                a["x"] -= ux * push * wa
                a["y"] -= uy * push * wa
                b["x"] += ux * push * wb
                b["y"] += uy * push * wb
                moved = True
        if spring > 0.0:
            for n in nodes:
                anchor = anchors.get(n["id"])
                if anchor is None:
                    continue
                n["x"] += (anchor[0] - n["x"]) * spring
                n["y"] += (anchor[1] - n["y"]) * spring
        if not moved and spring <= 0.0:
            break
    # Centre the finished layout on its own bounding box, so the map sits in
    # the middle of the frame instead of drifting toward the heavy wedges.
    xs = [n["x"] for n in nodes]
    ys = [n["y"] for n in nodes]
    cx = (min(xs) + max(xs)) / 2.0
    cy = (min(ys) + max(ys)) / 2.0
    for n in nodes:
        n["x"] = round(n["x"] - cx, 2)
        n["y"] = round(n["y"] - cy, 2)
        n["z"] = _bulge(n["x"], n["y"])


def split_explorer() -> None:
    html = EXPLORER_HTML.read_text(encoding="utf-8")
    head, _, rest = html.partition(SCRIPT_OPEN)
    script, _, tail = rest.rpartition(SCRIPT_CLOSE)
    if not script:
        raise SystemExit("could not find inline <script> in story_explorer.html")
    out = OUT_DIR / "explorer"
    out.mkdir(parents=True, exist_ok=True)
    (out / "explorer.js").write_text(script, encoding="utf-8")
    parts = [head, '<script src="./explorer.js" defer>', SCRIPT_CLOSE, tail]
    (out / "index.html").write_text("".join(parts), encoding="utf-8")


def main() -> int:
    # Rebuild the explorer first so the split copy is never stale.
    if bse.main() != 0:
        return 1
    stories = bse.load_stories()
    data = build_parent_data(stories)
    out = OUT_DIR / "data"
    out.mkdir(parents=True, exist_ok=True)
    (out / "stories.json").write_text(
        json.dumps(data, ensure_ascii=False), encoding="utf-8"
    )
    split_explorer()
    n = len(data["stories"])
    t = len(data["topics"])
    voiced = sum(1 for story in data["stories"] if "audio" in story)
    print(f"wrote pilot_site: {n} stories ({voiced} voiced), {t} topics -> {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
