"""Build the deployable buju.ai/pilot assets from the pilot story library.

Outputs (under story_definitions/preview/pilot_site/):

  data/stories.json      parent-facing story data: full prose + choices + slots,
                         but NO build_record / gate findings / R&D internals.
  explorer/index.html    the admin story explorer, with its script split out to
  explorer/explorer.js   an external file so it can ship under the website's
                         CSP (script-src 'self' forbids inline scripts).

Run from the repo root as:  python scripts/build_pilot_site.py
(never `python -m`, never with PYTHONPATH=. — the repo's logging/ package
shadows stdlib logging when the root is sys.path[0]).

The parent page itself (HTML/CSS/JS) is hand-authored in the buju_website
repo under pilot/ — this script only produces the data + explorer artifacts
that get copied there.
"""

from __future__ import annotations

import json
import math
import sys
from pathlib import Path
from typing import Any

import build_story_explorer as bse  # same directory; reuse loader + validator
import story_audio_chunks

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "story_definitions" / "preview" / "pilot_site"
EXPLORER_HTML = REPO_ROOT / "story_definitions" / "preview" / "story_explorer.html"
AUDIO_MANIFEST = REPO_ROOT / "story_definitions" / "audio_manifest.json"

# Split markers for the single inline <script> in the built explorer.
# split/join only — no regex, no .replace() (see STORY_EXPLORER_SPEC.md).
SCRIPT_OPEN = "<script>"
SCRIPT_CLOSE = "</script>"


def _reading_minutes(story: dict[str, Any]) -> int:
    """Rough read-aloud minutes for the longest path (~140 wpm aloud)."""
    segments = {seg["id"]: seg for seg in story["segments"]}
    words_a = 0
    words_b = 0
    for seg_id, seg in segments.items():
        n = len(seg["text"].split())
        if seg_id.endswith("a"):
            words_a += n
        elif seg_id.endswith("b"):
            words_b += n
        else:
            words_a += n
            words_b += n
    minutes = max(words_a, words_b) / 140.0
    return max(2, round(minutes))


def load_audio_manifest() -> dict[str, Any]:
    """Narration clips generated by generate_story_audio.py, or {} when no
    story has been voiced yet."""
    if not AUDIO_MANIFEST.is_file():
        return {}
    with open(AUDIO_MANIFEST, encoding="utf-8") as f:
        return json.load(f)


def story_audio_field(
    story: dict[str, Any], manifest_entry: dict[str, Any]
) -> dict[str, Any] | None:
    """The parent-facing `audio` field for one voiced story, or None when the
    manifest is stale (story prose changed since generation — regenerate).

    Per unit (segment or choice question), a list over paragraph chunks:
    {"i": chunk index, "file": mp3 under /pilot/audio/<story_id>/,
     "has_slot": chunk contains a {slot} so the player re-voices it live
     with the chosen name (this mp3 is the default-name fallback)}.
    """
    slots = story.get("slots") or {}
    unit_prose = {segment["id"]: segment["text"] for segment in story["segments"]}
    unit_prose.update(
        (choice_point["id"], choice_point["question"])
        for choice_point in story["choice_points"]
    )
    manifest_segments = manifest_entry.get("segments", {})
    stamped_segments: dict[str, list[dict[str, Any]]] = {}
    for unit_id, prose in unit_prose.items():
        chunks = story_audio_chunks.paragraph_chunks(prose)
        manifest_chunks = manifest_segments.get(unit_id)
        if manifest_chunks is None or len(manifest_chunks) != len(chunks):
            print(
                f"WARNING: audio manifest is stale for {story['id']} "
                f"(unit {unit_id}) — skipping its audio; re-run "
                f"generate_story_audio.py for this story"
            )
            return None
        stamped_segments[unit_id] = [
            {
                "i": chunk_entry["i"],
                "file": chunk_entry["file"],
                "has_slot": bool(
                    story_audio_chunks.declared_slot_tokens(chunks[chunk_entry["i"]], slots)
                ),
            }
            for chunk_entry in manifest_chunks
        ]
    return {
        # voice_id / model_id / speed ride along so the read-time
        # name-narration endpoint re-voices chunks with the same voice.
        "voice_id": manifest_entry["voice_id"],
        "model_id": manifest_entry["model_id"],
        "speed": manifest_entry.get("speed", 1.0),
        "segments": stamped_segments,
    }


def build_parent_data(stories: list[dict[str, Any]]) -> dict[str, Any]:
    registry = bse.load_default_registry()
    audio_manifest = load_audio_manifest()
    topics: dict[str, str] = {}
    out_stories: list[dict[str, Any]] = []
    for story in sorted(stories, key=lambda s: (s["title"])):
        topic_id = story["topics"]["knowledge_domain"]
        if topic_id not in topics:
            node = registry.get_node(topic_id)
            topics[topic_id] = node.display_name if node else topic_id.split(".")[-1]
        segments = {
            seg["id"]: {"text": seg["text"], "next": seg["next"]}
            for seg in story["segments"]
        }
        choices = {
            cp["id"]: {
                "question": cp["question"],
                "rejoins": cp["rejoins"],
                "options": [
                    {
                        "say_word": opt["say_word"],
                        "label": opt["label"],
                        "next_segment": opt["next_segment"],
                        "sets_slots": opt.get("sets_slots", {}),
                    }
                    for opt in cp["options"]
                ],
            }
            for cp in story["choice_points"]
        }
        slots = {
            name: {
                "role": slot["role"],
                "kind": slot["kind"],
                "ask_child": slot["ask_child"],
                "default": slot["default"],
            }
            for name, slot in story["slots"].items()
        }
        parent_story = {
            "id": story["id"],
            "title": story["title"],
            "age_band": story["age_band"],
            "topic": topic_id,
            "depth": story["depth"],
            "minutes": _reading_minutes(story),
            "start": story["start_segment"],
            "segments": segments,
            "choices": choices,
            "slots": slots,
        }
        if story["id"] in audio_manifest:
            audio_field = story_audio_field(story, audio_manifest[story["id"]])
            if audio_field is not None:
                parent_story["audio"] = audio_field
        out_stories.append(parent_story)
    return {
        "topics": topics,
        "stories": out_stories,
        "graph": build_parent_graph(stories),
    }


# Similarity super-groups for the parent map: wedges laid out in this order
# around the disc, so neighbouring wedges hold related themes (space→earth→
# water→life→food→mind→arts→machines→space). Categories inside a group
# cluster tightly; their deep dives ring each category. Every category in
# build_story_explorer.PILOT_CATEGORIES must appear exactly once here —
# the build fails loudly if the two lists drift apart.
_KD = "knowledge_domain."
PARENT_MAP_GROUPS: list[tuple[str, list[str]]] = [
    ("space", ["planets", "the_solar_system", "the_moon", "the_sun",
               "stars_and_constellations", "black_holes", "comets_and_meteors",
               "gravity", "astronauts_and_space_travel", "day_and_night"]),
    ("earth", ["volcanoes", "earthquakes", "plate_tectonics",
               "rocks_and_minerals", "islands", "weather", "maps_and_globes"]),
    ("water", ["oceans_and_tides", "ocean_animals", "whales_and_dolphins",
               "frogs_and_amphibians"]),
    ("life", ["insects", "birds", "rainforests", "dinosaurs"]),
    ("food", ["farms_and_food"]),
    ("mind", ["the_brain", "sleep_and_dreams"]),
    ("arts", ["musical_instruments", "sound_and_echoes", "drawing_and_animation",
              "theater_and_pretending", "shapes_and_symmetry"]),
    ("machines", ["computers_and_code", "robots", "engines_and_vehicles",
                  "magnets"]),
]

# Front-hemisphere disc layout: flat enough that nothing hides behind
# anything under the map's clamped "fake" rotation, with a gentle z bulge
# for parallax. y is compressed to suit the wide viewBox.
CAT_RING_INNER = 178.0      # categories alternate between two rings so
CAT_RING_OUTER = 256.0      # neighbouring clusters never share a ring
Y_SQUASH = 0.72
BULGE_RADIUS = 380.0


def _child_ring(count: int) -> float:
    """Deep-dive ring radius, scaled so siblings keep ~30px spacing."""
    return min(64.0, max(40.0, 5.0 * count))


def _disc_positions() -> dict[str, tuple[float, float, float]]:
    grouped = [(g, cats) for g, cats in PARENT_MAP_GROUPS]
    listed = [c for _, cats in grouped for c in cats]
    expected = sorted(bse.PILOT_CATEGORIES)
    if sorted(_KD + c for c in listed) != expected:
        missing = set(expected) - {_KD + c for c in listed}
        extra = {_KD + c for c in listed} - set(expected)
        raise SystemExit(
            f"PARENT_MAP_GROUPS out of sync with PILOT_CATEGORIES: "
            f"missing={sorted(missing)} extra={sorted(extra)}"
        )
    total = len(listed)
    pos: dict[str, tuple[float, float, float]] = {}
    theta = 0.0
    ring_flip = 0
    for _, cats in grouped:
        wedge = 2.0 * math.pi * (len(cats) / total)
        inner_span = wedge * 0.80
        start = theta + (wedge - inner_span) / 2.0
        for i, cat in enumerate(cats):
            frac = 0.5 if len(cats) == 1 else i / (len(cats) - 1)
            a = start + inner_span * frac
            # global inner/outer alternation: consecutive categories land on
            # different rings, so clusters interleave instead of colliding
            r = CAT_RING_INNER if ring_flip % 2 == 0 else CAT_RING_OUTER
            ring_flip += 1
            x = r * math.cos(a)
            y = r * math.sin(a) * Y_SQUASH
            pos[_KD + cat] = (round(x, 2), round(y, 2), a)
        theta += wedge
    return pos


def _bulge(x: float, y: float) -> float:
    d2 = x * x + (y / Y_SQUASH) ** 2
    return round(0.5 * math.sqrt(max(0.0, BULGE_RADIUS ** 2 - d2)) - 60.0, 2)


def build_parent_graph(stories: list[dict[str, Any]]) -> dict[str, Any]:
    """The topic map for the parent page: positions + edges + story counts.

    Unlike the admin explorer's full sphere, the parent map is a clustered
    front-facing disc: similarity super-groups sit in adjacent wedges,
    categories cluster inside their wedge, deep dives ring their category,
    and a mild z bulge gives parallax under the page's clamped rotation.
    Ships ONLY parent-safe fields — no framing / vocabulary / avoid lists.
    """
    expl = bse.build_explorer_data(stories)  # reuse counts, names, edges
    by_id = {t["id"]: t for t in expl["topics"]}
    cat_pos = _disc_positions()

    nodes: list[dict[str, Any]] = []
    for t in expl["topics"]:
        if t["parent"] is None:
            if t["id"] not in cat_pos:
                continue
            x, y, _a = cat_pos[t["id"]]
        else:
            px, py, pa = cat_pos[t["parent"]]
            siblings = sorted(
                s["id"] for s in expl["topics"] if s["parent"] == t["parent"]
            )
            idx = siblings.index(t["id"])
            count = len(siblings)
            # full ring around the category, rotated to face outward first
            rc = _child_ring(count)
            a = pa + idx * (2.0 * math.pi / count)
            x = round(px + rc * math.cos(a), 2)
            y = round(py + rc * math.sin(a) * Y_SQUASH, 2)
        nodes.append(
            {
                "id": t["id"],
                "name": t["display_name"],
                "x": x,
                "y": y,
                "z": _bulge(x, y),
                "cluster": t["cluster"],
                "parent": t["parent"],
                "stories": t["stories"],
            }
        )

    _relax(nodes)

    kept = {n["id"] for n in nodes}
    edges = [
        {"source": e["source"], "target": e["target"]}
        for e in expl["edges"]
        if e["source"] in kept and e["target"] in kept
    ]
    return {"nodes": nodes, "edges": edges}


MIN_NODE_SPACING = 33.0


def _relax(nodes: list[dict[str, Any]], rounds: int = 60) -> None:
    """Push overlapping nodes apart. Categories stay pinned so the wedge
    structure holds; only deep dives drift. Deterministic (no randomness)."""
    for _ in range(rounds):
        moved = False
        for i in range(len(nodes)):
            for j in range(i + 1, len(nodes)):
                a, b = nodes[i], nodes[j]
                dx = b["x"] - a["x"]
                dy = b["y"] - a["y"]
                d = math.sqrt(dx * dx + dy * dy)
                if d >= MIN_NODE_SPACING:
                    continue
                if d < 1e-6:
                    dx, dy, d = 1.0, 0.5, 1.118
                push = (MIN_NODE_SPACING - d) / 2.0
                ux, uy = dx / d, dy / d
                a_pinned = a["parent"] is None
                b_pinned = b["parent"] is None
                if a_pinned and b_pinned:
                    continue
                if not a_pinned:
                    a["x"] = round(a["x"] - ux * (push * (2 if b_pinned else 1)), 2)
                    a["y"] = round(a["y"] - uy * (push * (2 if b_pinned else 1)), 2)
                if not b_pinned:
                    b["x"] = round(b["x"] + ux * (push * (2 if a_pinned else 1)), 2)
                    b["y"] = round(b["y"] + uy * (push * (2 if a_pinned else 1)), 2)
                moved = True
        if not moved:
            break
    for n in nodes:
        n["z"] = _bulge(n["x"], n["y"])


def split_explorer() -> None:
    html = EXPLORER_HTML.read_text(encoding="utf-8")
    head, _, rest = html.partition(SCRIPT_OPEN)
    script, _, tail = rest.rpartition(SCRIPT_CLOSE)
    if not script:
        raise SystemExit("could not find inline <script> in story_explorer.html")
    out = OUT_DIR / "explorer"
    out.mkdir(parents=True, exist_ok=True)
    (out / "explorer.js").write_text(script, encoding="utf-8")
    parts = [head, '<script src="./explorer.js" defer>', SCRIPT_CLOSE, tail]
    (out / "index.html").write_text("".join(parts), encoding="utf-8")


def main() -> int:
    # Rebuild the explorer first so the split copy is never stale.
    if bse.main() != 0:
        return 1
    stories = bse.load_stories()
    data = build_parent_data(stories)
    out = OUT_DIR / "data"
    out.mkdir(parents=True, exist_ok=True)
    (out / "stories.json").write_text(
        json.dumps(data, ensure_ascii=False), encoding="utf-8"
    )
    split_explorer()
    n = len(data["stories"])
    t = len(data["topics"])
    voiced = sum(1 for story in data["stories"] if "audio" in story)
    print(f"wrote pilot_site: {n} stories ({voiced} voiced), {t} topics -> {OUT_DIR}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
